import React, { useState } from 'react';
import { X, Download, Copy, Check, FileText, Code2, ShieldAlert } from 'lucide-react';
import { AnalysisResult } from '../types';
import { audioFX } from '../utils/audioFX';

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  result: AnalysisResult | null;
}

export const ExportModal: React.FC<ExportModalProps> = ({ isOpen, onClose, result }) => {
  const [activeTab, setActiveTab] = useState<'markdown' | 'json'>('markdown');
  const [isCopied, setIsCopied] = useState(false);

  if (!isOpen || !result) return null;

  const generateMarkdown = () => {
    return `# SOLIS AI — EXECUTIVE INTELLIGENCE BRIEF
**Generated**: ${result.timestamp} | **Output ID**: ${result.id}
**Target Input**: ${result.title}
**Composite Rating**: ${result.compositeScore}/100 (${result.tierGrade})

---

## Executive Summary
${result.summaryParagraph}

### Sentiment & Tone Profile
- **Dominant Tone**: ${result.sentiment.overallTone}
- **Conviction & Optimism**: ${result.sentiment.positive}%
- **Constructive / Strategic**: ${result.sentiment.constructive}%
- **Objective / Neutral**: ${result.sentiment.neutral}%
- **Urgency / Escalation**: ${result.sentiment.urgent}%
- **Emotional Temperature**: ${result.sentiment.emotionalTemperature}°C

---

## Key Strategic Insights
${result.insights.map((ins, i) => `${i + 1}. **[${ins.impactLevel.toUpperCase()}] ${ins.title}** (${ins.confidence}% confidence)
   ${ins.detail}`).join('\n\n')}

---

## Actionable Optimizations & Rewrites
${result.suggestions.map((sug, i) => `### Optimization 0${i + 1}: ${sug.title}
- **Expected Impact**: ${sug.expectedGain} (Effort: ${sug.effort})
- **Strategic Rationale**: ${sug.rationale}
- **Synthesized Directive**:
  > "${sug.improvedVersion}"`).join('\n\n')}

---
*Generated by Solis AI Autonomous Luxury Intelligence Suite. SOC2 Type II Certified.*`;
  };

  const generateJSON = () => {
    return JSON.stringify(result, null, 2);
  };

  const contentToDisplay = activeTab === 'markdown' ? generateMarkdown() : generateJSON();

  const handleCopy = () => {
    audioFX.playClick();
    navigator.clipboard.writeText(contentToDisplay);
    setIsCopied(true);
    setTimeout(() => setIsCopied(false), 2000);
  };

  const handleDownload = () => {
    audioFX.playClick();
    const blob = new Blob([contentToDisplay], {
      type: activeTab === 'markdown' ? 'text/markdown;charset=utf-8' : 'application/json;charset=utf-8',
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Solis_AI_Intelligence_${result.id}.${activeTab === 'markdown' ? 'md' : 'json'}`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 overflow-y-auto flex items-center justify-center p-4">
      {/* Backdrop */}
      <div 
        className="fixed inset-0 bg-black/80 backdrop-blur-md transition-opacity"
        onClick={() => {
          audioFX.playClick();
          onClose();
        }}
      />

      {/* Modal Dialog */}
      <div className="relative w-full max-w-3xl glass-surface rounded-3xl border border-vanilla/25 shadow-2xl p-6 sm:p-8 z-10 animate-in fade-in zoom-in-95 duration-200 bg-[#1A170B]/95 text-vanilla">
        
        {/* Header */}
        <div className="flex items-center justify-between pb-4 border-b border-vanilla/15">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-xl bg-tangerine/15 text-tangerine border border-tangerine/30 flex items-center justify-center">
              <Download className="w-4 h-4" />
            </div>
            <div>
              <h3 className="text-base font-semibold text-vanilla tracking-tight">
                Export Executive Dossier
              </h3>
              <p className="text-xs text-vanilla-muted">
                Distribute audit telemetry and strategic directives
              </p>
            </div>
          </div>

          <button
            onClick={() => {
              audioFX.playClick();
              onClose();
            }}
            className="p-2 rounded-xl text-vanilla-muted hover:text-vanilla hover:bg-brunswick/40 border border-transparent hover:border-vanilla/15 transition-all"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Tab Controls */}
        <div className="flex items-center justify-between my-4">
          <div className="flex items-center gap-1.5 p-1 rounded-xl bg-darkbrown/80 border border-vanilla/10">
            <button
              onClick={() => {
                audioFX.playClick();
                setActiveTab('markdown');
              }}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium transition-all ${
                activeTab === 'markdown'
                  ? 'bg-tangerine text-darkbrown-deep font-bold shadow-sm'
                  : 'text-vanilla-muted hover:text-vanilla'
              }`}
            >
              <FileText className="w-3.5 h-3.5" />
              <span>Executive Markdown</span>
            </button>

            <button
              onClick={() => {
                audioFX.playClick();
                setActiveTab('json');
              }}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium transition-all ${
                activeTab === 'json'
                  ? 'bg-tangerine text-darkbrown-deep font-bold shadow-sm'
                  : 'text-vanilla-muted hover:text-vanilla'
              }`}
            >
              <Code2 className="w-3.5 h-3.5" />
              <span>Raw JSON Stream</span>
            </button>
          </div>

          <div className="hidden sm:flex items-center gap-1 text-[11px] font-mono text-vanilla-muted">
            <ShieldAlert className="w-3.5 h-3.5 text-tangerine" />
            <span>Encrypted Token Stream</span>
          </div>
        </div>

        {/* Code Preview Frame */}
        <div className="relative rounded-2xl bg-darkbrown/95 border border-vanilla/15 p-4 max-h-72 overflow-y-auto font-mono text-xs text-vanilla-soft/90 leading-relaxed shadow-inner">
          <pre className="whitespace-pre-wrap">{contentToDisplay}</pre>
        </div>

        {/* Actions Footer */}
        <div className="mt-6 pt-4 border-t border-vanilla/15 flex flex-wrap items-center justify-between gap-3">
          <div className="text-xs font-mono text-vanilla-muted">
            Ready for board briefing & stakeholder distribution
          </div>

          <div className="flex items-center gap-2.5">
            <button
              onClick={handleCopy}
              className="px-4 py-2 rounded-xl text-xs font-medium text-vanilla-soft hover:text-vanilla bg-brunswick/50 hover:bg-brunswick/70 border border-vanilla/20 transition-all flex items-center gap-2"
            >
              {isCopied ? (
                <>
                  <Check className="w-3.5 h-3.5 text-tangerine" />
                  <span className="text-tangerine font-semibold">Copied to Clipboard</span>
                </>
              ) : (
                <>
                  <Copy className="w-3.5 h-3.5" />
                  <span>Copy Content</span>
                </>
              )}
            </button>

            <button
              onClick={handleDownload}
              className="btn-tangerine-glow px-4 py-2 rounded-xl text-xs font-semibold text-white flex items-center gap-2 shadow-tangerine-sm"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Download File (.{activeTab === 'markdown' ? 'md' : 'json'})</span>
            </button>
          </div>
        </div>

      </div>
    </div>
  );
};
